//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProFinalEstudiantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIANTE
    {
        public decimal ID { get; set; }
        public string CARNET { get; set; }
        public string NOMBRE { get; set; }
        public string FECHA_NACIMIENTO { get; set; }
        public string FECHA_REGISTRO { get; set; }
    
        public virtual COLA_ESTUDIANTES COLA_ESTUDIANTES { get; set; }
        public virtual INSCRIPCION_ESTUDIANTES INSCRIPCION_ESTUDIANTES { get; set; }
    }
}
